name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        pip install --user buildozer cython
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Setup Python path (for Buildozer)
      run: |
        # Buildozer padrão às vezes procura 'python'. Isso cria um link simbólico para o python3
        sudo ln -s /usr/bin/python3 /usr/bin/python || true

    - name: Accept Android licenses
      run: |
        yes | $HOME/.local/share/buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Prometheus-APK
        path: bin/*.apk
