name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
        pip install --user buildozer cython
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Setup Python path (for Buildozer)
      run: |
        sudo ln -s /usr/bin/python3 /usr/bin/python || true

    # AQUI É A MÁGICA PARA RESOLVER DE VEZ
    - name: Build APK
      run: |
        mkdir -p $HOME/.local/share/buildozer/android/platform/android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.local/share/buildozer/android/platform/android-sdk/licenses/android-sdk-license
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Prometheus-APK
        path: bin/*.apk
